# Generated by Django 6.0.6 on 2026-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.DecimalField(auto_created=True, decimal_places=1, max_digits=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
