# Generated by Django 6.0.6 on 2026-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.DecimalField(auto_created=True, decimal_places=2, max_digits=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
