import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()


def populate_database():
    from app.models import Album, Song
    
    print("Populating the database with albums and songs...")

    sh1, _ = Album.objects.get_or_create(name='Silent Hill 1', album_cover='Silent_Hill_Complete_Soundtrack_Ultimate_Edition_wthiem.jpg')
    sh2, _ = Album.objects.get_or_create(name='Silent Hill 2', album_cover='Silent_Hill_2_Complete_Soundtrack_Ultimate_Edition_uosyfi.jpg')
    sh3, _ = Album.objects.get_or_create(name='Silent Hill 3', album_cover='Silent_Hill_3_Complete_Sountrack_Ultimate_Edition_ajaiow.jpg')

# Silent Hill 1
    Song.objects.get_or_create(album=sh1, title='Silent Hill', audio_file='Silent_Hill_CST_-_1.01_-_Silent_Hill_r4brts.flac')
    Song.objects.get_or_create(album=sh1, title='Arrival', audio_file='Silent_Hill_CST_-_1.02_-_Arrival_umlyup.flac')
    Song.objects.get_or_create(album=sh1, title='Led into Madness', audio_file='Silent_Hill_CST_-_1.03_-_Led_into_Madness_zusd2j.flac')
    Song.objects.get_or_create(album=sh1, title='Meeting Cybil', audio_file='Silent_Hill_CST_-_1.04_-_Meeting_Cybil_es4grp.flac')
    Song.objects.get_or_create(album=sh1, title='No Dream', audio_file='Silent_Hill_CST_-_1.05_-_No_Dream_uazbfb.flac')
    Song.objects.get_or_create(album=sh1, title='Darkness Falls Again', audio_file='Silent_Hill_CST_-_1.06_-_Darkness_Falls_Again_w11jtz.flac')
    Song.objects.get_or_create(album=sh1, title='Running in the Hallways', audio_file='Silent_Hill_CST_-_1.07_-_Running_in_the_Hallways_sczzb1.flac')
    Song.objects.get_or_create(album=sh1, title='The Clock Passage', audio_file='Silent_Hill_CST_-_1.08_-_The_Clock_Passage_pq3b5d.flac')
    Song.objects.get_or_create(album=sh1, title='Midwich Nightmare', audio_file='Silent_Hill_CST_-_1.09_-_Midwich_Nightmare_tqrkdq.flac')
    Song.objects.get_or_create(album=sh1, title='The Beast', audio_file='Silent_Hill_CST_-_1.10_-_The_Beast_qwfsyw.flac')
    Song.objects.get_or_create(album=sh1, title='Apparition', audio_file='Silent_Hill_CST_-_1.11_-_Apparition_ibvy9x.flac')
    Song.objects.get_or_create(album=sh1, title='Morning Recess', audio_file='Silent_Hill_CST_-_2.01_-_Morning_Recess_d4bsf6.flac')
    Song.objects.get_or_create(album=sh1, title='Woman at the Altar', audio_file='Silent_Hill_CST_-_2.02_-_Woman_at_the_Altar_wlcrlt.flac')
    Song.objects.get_or_create(album=sh1, title='Sermon', audio_file='Silent_Hill_CST_-_2.03_-_Sermon_bna0cy.flac')
    Song.objects.get_or_create(album=sh1, title='Silent Streets', audio_file='Silent_Hill_CST_-_2.04_-_Silent_Streets_kkk4m1.flac')
    Song.objects.get_or_create(album=sh1, title='The Police Station', audio_file='Silent_Hill_CST_-_2.05_-_The_Police_Station_eur0ja.flac')
    Song.objects.get_or_create(album=sh1, title='Another Survivor', audio_file='Silent_Hill_CST_-_2.06_-_Another_Survivor_cpx1zn.flac')
    Song.objects.get_or_create(album=sh1, title='Dr. Kaufmann', audio_file='Silent_Hill_CST_-_2.07_-_Dr._Kaufmann_svdnlv.flac')
    Song.objects.get_or_create(album=sh1, title='Alchemilla Echoes', audio_file='Silent_Hill_CST_-_2.08_-_Alchemilla_Echoes_vgmehg.flac')
    Song.objects.get_or_create(album=sh1, title='The Generator', audio_file='Silent_Hill_CST_-_2.09_-_The_Generator_v1rhln.flac')
    Song.objects.get_or_create(album=sh1, title='Code Blue', audio_file='Silent_Hill_CST_-_2.10_-_Code_Blue_vuqget.flac')
    Song.objects.get_or_create(album=sh1, title='Shadows in the Basement', audio_file='Silent_Hill_CST_-_2.11_-_Shadows_in_the_Basement_qusj4s.flac')
    Song.objects.get_or_create(album=sh1, title='Rescued', audio_file='Silent_Hill_CST_-_2.12_-_Rescued_u1oiga.flac')
    Song.objects.get_or_create(album=sh1, title="Dahlia's Guidance", audio_file='Silent_Hill_CST_-_2.13_-_Dahlia_s_Guidance_l5ngge.flac')
    Song.objects.get_or_create(album=sh1, title='Path of Torment', audio_file='Silent_Hill_CST_-_3.01_-_Path_of_Torment_tbfxj7.flac')
    Song.objects.get_or_create(album=sh1, title='Cybil Returns', audio_file='Silent_Hill_CST_-_3.02_-_Cybil_Returns_be3mtx.flac')
    Song.objects.get_or_create(album=sh1, title='Secret Shrine', audio_file='Silent_Hill_CST_-_3.03_-_Secret_Shrine_ivdgby.flac')
    Song.objects.get_or_create(album=sh1, title='Shopping Maul', audio_file='Silent_Hill_CST_-_3.04_-_Shopping_Maul_mk2e5x.flac')
    Song.objects.get_or_create(album=sh1, title='Wormsign', audio_file='Silent_Hill_CST_-_3.05_-_Wormsign_gjhhpq.flac')
    Song.objects.get_or_create(album=sh1, title='Bad to Worse', audio_file='Silent_Hill_CST_-_3.06_-_Bad_to_Worse_uq2xto.flac')
    Song.objects.get_or_create(album=sh1, title='Another Way', audio_file='Silent_Hill_CST_-_3.07_-_Another_Way_euaysv.flac')
    Song.objects.get_or_create(album=sh1, title='Before the Storm', audio_file='Silent_Hill_CST_-_3.08_-_Before_the_Storm_g1tjis.flac')
    Song.objects.get_or_create(album=sh1, title='Floatstung', audio_file='Silent_Hill_CST_-_3.09_-_Floatstung_psinua.flac')
    Song.objects.get_or_create(album=sh1, title='The Sewer Passage', audio_file='Silent_Hill_CST_-_4.01_-_The_Sewer_Passage_mhxdxm.flac')
    Song.objects.get_or_create(album=sh1, title='Night Owl', audio_file='Silent_Hill_CST_-_4.02_-_Night_Owl_kcacr4.flac')
    Song.objects.get_or_create(album=sh1, title="Screamer's Revenge", audio_file='Silent_Hill_CST_-_4.03_-_Screamer_s_Revenge_ncm6mp.flac')
    Song.objects.get_or_create(album=sh1, title='Rust Darkness', audio_file='Silent_Hill_CST_-_4.04_-_Rust_Darkness_ohsaq5.flac')
    Song.objects.get_or_create(album=sh1, title='The Boat Meeting', audio_file='Silent_Hill_CST_-_4.05_-_The_Boat_Meeting_aueblg.flac')
    Song.objects.get_or_create(album=sh1, title='Pier 666', audio_file='Silent_Hill_CST_-_4.06_-_Pier_666_pdedzc.flac')
    Song.objects.get_or_create(album=sh1, title='Sealed Fate', audio_file='Silent_Hill_CST_-_4.07_-_Sealed_Fate_zpmnwz.flac')
    Song.objects.get_or_create(album=sh1, title='Urgency', audio_file='Silent_Hill_CST_-_5.01_-_Urgency_tmmgbq.flac')
    Song.objects.get_or_create(album=sh1, title='Filth & Pain', audio_file='Silent_Hill_CST_-_5.02_-_Filth_Pain_tgkytd.flac')
    Song.objects.get_or_create(album=sh1, title='Sickly Fairground', audio_file='Silent_Hill_CST_-_5.03_-_Sickly_Fairground_s3mbpc.flac')
    Song.objects.get_or_create(album=sh1, title='A Joyful Ride', audio_file='Silent_Hill_CST_-_5.04_-_A_Joyful_Ride_fcyqul.flac')
    Song.objects.get_or_create(album=sh1, title='Carousel Battle', audio_file='Silent_Hill_CST_-_5.05_-_Carousel_Battle_up9ex1.flac')
    Song.objects.get_or_create(album=sh1, title='Expelled', audio_file='Silent_Hill_CST_-_5.06_-_Expelled_leqf83.flac')
    Song.objects.get_or_create(album=sh1, title='Confronting Alessa', audio_file='Silent_Hill_CST_-_5.07_-_Confronting_Alessa_ceaql8.flac')
    Song.objects.get_or_create(album=sh1, title="Dahlia's Turn", audio_file='Silent_Hill_CST_-_5.08_-_Dahlia_s_Turn_etwmzr.flac')
    Song.objects.get_or_create(album=sh1, title='Arriving Nowhere', audio_file='Silent_Hill_CST_-_6.01_-_Arriving_Nowhere_tutbvq.flac')
    Song.objects.get_or_create(album=sh1, title="Lisa's Confession", audio_file='Silent_Hill_CST_-_6.02_-_Lisa_s_Confession_tcxt6c.flac')
    Song.objects.get_or_create(album=sh1, title='Summoned', audio_file='Silent_Hill_CST_-_6.03_-_Summoned_qtopqp.flac')
    Song.objects.get_or_create(album=sh1, title='Amalgam of Fear', audio_file='Silent_Hill_CST_-_6.04_-_Amalgam_of_Fear_rok5ag.flac')
    Song.objects.get_or_create(album=sh1, title='Acceptance', audio_file='Silent_Hill_CST_-_6.05_-_Acceptance_skntjn.flac')
    Song.objects.get_or_create(album=sh1, title='Tears of Blood', audio_file='Silent_Hill_CST_-_6.06_-_Tears_of_Blood_dxgtjt.flac')
    Song.objects.get_or_create(album=sh1, title='Further Down', audio_file='Silent_Hill_CST_-_6.07_-_Further_Down_bp91va.flac')
    Song.objects.get_or_create(album=sh1, title='Shedded Light', audio_file='Silent_Hill_CST_-_6.08_-_Shedded_Light_rmrlr2.flac')
    Song.objects.get_or_create(album=sh1, title='The Final Lock', audio_file='Silent_Hill_CST_-_6.09_-_The_Final_Lock_cwpgpt.flac')
    Song.objects.get_or_create(album=sh1, title='Metamorphosis', audio_file='Silent_Hill_CST_-_6.10_-_Metamorphosis_oaspvv.flac')
    Song.objects.get_or_create(album=sh1, title='Incubus', audio_file='Silent_Hill_CST_-_6.11_-_Incubus_pvsfzm.flac')
    Song.objects.get_or_create(album=sh1, title="Alessa's Gift", audio_file='Silent_Hill_CST_-_7.01_-_Alessa_s_Gift_zglng5.flac')
    Song.objects.get_or_create(album=sh1, title='Running Out', audio_file='Silent_Hill_CST_-_7.02_-_Running_Out_buiqcm.flac')
    Song.objects.get_or_create(album=sh1, title='Tears of...', audio_file='Silent_Hill_CST_-_7.03_-_Tears_of..._eawv7t.flac')
    Song.objects.get_or_create(album=sh1, title='New Life', audio_file='Silent_Hill_CST_-_7.04_-_New_Life_j7ihh1.flac')
    Song.objects.get_or_create(album=sh1, title='Killing Time', audio_file='Silent_Hill_CST_-_7.05_-_Killing_Time_msyohn.flac')
    Song.objects.get_or_create(album=sh1, title='She', audio_file='Silent_Hill_CST_-_7.06_-_She_zn75yt.flac')
    Song.objects.get_or_create(album=sh1, title='Esperándote', audio_file='Silent_Hill_CST_-_7.07_-_Esperándote_nt81hh.flac')
    Song.objects.get_or_create(album=sh1, title='Silent Hill (Otherside)', audio_file='Silent_Hill_CST_-_7.08_-_Silent_Hill_Otherside_na2kpz.flac')
    Song.objects.get_or_create(album=sh1, title='Results', audio_file='Silent_Hill_CST_-_7.09_-_Results_fmohln.flac')
    Song.objects.get_or_create(album=sh1, title='Azusa Igo', audio_file='Silent_Hill_CST_-_8.01_-_Azusa_Igo_uwq8zi.flac')
    Song.objects.get_or_create(album=sh1, title='Silent Hill (estudio)', audio_file='Silent_Hill_CST_-_8.02_-_Silent_Hill_estudio_re7lu9.flac')
    Song.objects.get_or_create(album=sh1, title='Anaconda', audio_file='Silent_Hill_CST_-_8.03_-_Anaconda_k0zhlo.flac')
    Song.objects.get_or_create(album=sh1, title='Tussock', audio_file='Silent_Hill_CST_-_8.04_-_Tussock_rx11t1.flac')
    Song.objects.get_or_create(album=sh1, title='UFO Ending', audio_file='Silent_Hill_CST_-_8.05_-_UFO_Ending_ggecyx.flac')


# Silent Hill 2
    Song.objects.get_or_create(album=sh2, title='Begin Nightmare', audio_file='Silent_Hill_2_CST_-_1.00_-_Begin_Nightmare_vndhxd.flac')
    Song.objects.get_or_create(album=sh2, title='Mirrored Guilt', audio_file='Silent_Hill_2_CST_-_1.01_-_Mirrored_Guilt_y3jna3.flac')
    Song.objects.get_or_create(album=sh2, title="Mary's Invitation", audio_file='Silent_Hill_2_CST_-_1.02_-_Mary_s_Invitation_u9cpjl.flac')
    Song.objects.get_or_create(album=sh2, title='Wishful Thinking', audio_file='Silent_Hill_2_CST_-_1.03_-_Wishful_Thinking_rbtlhe.flac')
    Song.objects.get_or_create(album=sh2, title='The Forest Trail', audio_file='Silent_Hill_2_CST_-_1.04_-_The_Forest_Trail_dglags.flac')
    Song.objects.get_or_create(album=sh2, title='Looking for Mommy', audio_file='Silent_Hill_2_CST_-_1.05_-_Looking_for_Mommy_zktzxx.flac')
    Song.objects.get_or_create(album=sh2, title='Toluca Graveyard', audio_file='Silent_Hill_2_CST_-_1.06_-_Toluca_Graveyard_my1uss.flac')
    Song.objects.get_or_create(album=sh2, title='Lurking in the Fog', audio_file='Silent_Hill_2_CST_-_1.07_-_Lurking_in_the_Fog_mpuu2h.flac')
    Song.objects.get_or_create(album=sh2, title='Mansion Horrors', audio_file='Silent_Hill_2_CST_-_2.00_-_Mansion_Horrors_fnjbuk.flac')
    Song.objects.get_or_create(album=sh2, title="Maria's Purpose", audio_file='Silent_Hill_2_CST_-_2.00b_-_Maria_s_Purpose_qopf6r.flac')
    Song.objects.get_or_create(album=sh2, title='The Stairwell', audio_file='Silent_Hill_2_CST_-_2.01_-_The_Stairwell_nrbhaf.flac')
    Song.objects.get_or_create(album=sh2, title='Ominous Hallway', audio_file='Silent_Hill_2_CST_-_2.02_-_Ominous_Hallway_ez6tvm.flac')
    Song.objects.get_or_create(album=sh2, title='Butterflies Secrets', audio_file='Silent_Hill_2_CST_-_2.03_-_Butterflies_Secrets_wvduni.flac')
    Song.objects.get_or_create(album=sh2, title='The 3rd Floor', audio_file='Silent_Hill_2_CST_-_2.04_-_The_3rd_Floor_x8kx9u.flac')
    Song.objects.get_or_create(album=sh2, title="Executioner's Handywork", audio_file='Silent_Hill_2_CST_-_2.05_-_Executioner_s_Handywork_zscvy5.flac')
    Song.objects.get_or_create(album=sh2, title='Meeting Eddie', audio_file='Silent_Hill_2_CST_-_2.06_-_Meeting_Eddie_sx5ivf.flac')
    Song.objects.get_or_create(album=sh2, title='Meeting Eddie (in-game)', audio_file='Silent_Hill_2_CST_-_2.06b_-_Meeting_Eddie_in-game_asgppt.flac')
    Song.objects.get_or_create(album=sh2, title='No (Fire) Escape', audio_file='Silent_Hill_2_CST_-_2.07_-_No_Fire_Escape_yup6mk.flac')
    Song.objects.get_or_create(album=sh2, title='Puzzles, Ashes, & Ghosts', audio_file='Silent_Hill_2_CST_-_2.08_-_Puzzles_Ashes_Ghosts_rsxhsk.flac')
    Song.objects.get_or_create(album=sh2, title='Lost Innocence', audio_file='Silent_Hill_2_CST_-_2.09_-_Lost_Innocence_d66wmg.flac')
    Song.objects.get_or_create(album=sh2, title='Lost Innocence (in-game)', audio_file='Silent_Hill_2_CST_-_2.09b_-_Lost_Innocence_in-game_tykf2w.flac')
    Song.objects.get_or_create(album=sh2, title="Pyramid Head's Lair", audio_file='Silent_Hill_2_CST_-_2.10_-_Pyramid_Head_s_Lair_htutga.flac')
    Song.objects.get_or_create(album=sh2, title='Combing Town West', audio_file='Silent_Hill_2_CST_-_3.01_-_Combing_Town_West_o5ipmi.flac')
    Song.objects.get_or_create(album=sh2, title="Mary's Twin", audio_file='Silent_Hill_2_CST_-_3.02_-_Mary_s_Twin_uun3bj.flac')
    Song.objects.get_or_create(album=sh2, title='Pizza & Bowling', audio_file='Silent_Hill_2_CST_-_3.03_-_Pizza_Bowling_p2nd4e.flac')
    Song.objects.get_or_create(album=sh2, title='Pizza & Bowling (in-game)', audio_file='Silent_Hill_2_CST_-_3.03b_-_Pizza_Bowling_in-game_ybcipa.flac')
    Song.objects.get_or_create(album=sh2, title="Heaven's Night", audio_file='Silent_Hill_2_CST_-_3.04_-_Heaven_s_Night_q1lsul.flac')
    Song.objects.get_or_create(album=sh2, title="Heaven's Night (in-game)", audio_file='Silent_Hill_2_CST_-_3.04b_-_Heaven_s_Night_in-game_lukwlk.flac')
    Song.objects.get_or_create(album=sh2, title='Brookhaven Insanity', audio_file='Silent_Hill_2_CST_-_4.01_-_Brookhaven_Insanity_d9ov9d.flac')
    Song.objects.get_or_create(album=sh2, title='Nurse Piper', audio_file='Silent_Hill_2_CST_-_4.02_-_Nurse_Piper_mvbe3m.flac')
    Song.objects.get_or_create(album=sh2, title='Laura', audio_file='Silent_Hill_2_CST_-_4.03_-_Laura_mzknbt.flac')
    Song.objects.get_or_create(album=sh2, title='Bed-Head', audio_file='Silent_Hill_2_CST_-_4.04_-_Bed-Head_kxpesw.flac')
    Song.objects.get_or_create(album=sh2, title='Nightmarehaven', audio_file='Silent_Hill_2_CST_-_4.05_-_Nightmarehaven_lheohi.flac')
    Song.objects.get_or_create(album=sh2, title='Hospital Predators', audio_file='Silent_Hill_2_CST_-_4.06_-_Hospital_Predators_frn4hf.flac')
    Song.objects.get_or_create(album=sh2, title='Running the Gauntlet', audio_file='Silent_Hill_2_CST_-_4.07_-_Running_the_Gantlet_nlflcu.flac')
    Song.objects.get_or_create(album=sh2, title='Failing Maria', audio_file='Silent_Hill_2_CST_-_4.08_-_Failing_Maria_u8w1oi.flac')
    Song.objects.get_or_create(album=sh2, title='The Tunnel Beckons', audio_file='Silent_Hill_2_CST_-_5.01_-_The_Tunnel_Beckons_cnmab4.flac')
    Song.objects.get_or_create(album=sh2, title='Prison of the Mind (Pt.1)', audio_file='Silent_Hill_2_CST_-_5.02_-_Prison_of_the_Mind_Pt.1_sqds9n.flac')
    Song.objects.get_or_create(album=sh2, title='The 1st Hole', audio_file='Silent_Hill_2_CST_-_5.03_-_The_1st_Hole_qekibh.flac')
    Song.objects.get_or_create(album=sh2, title='Prison of the Mind (Pt.2)', audio_file='Silent_Hill_2_CST_-_5.04_-_Prison_of_the_Mind_Pt.2_styaqn.flac')
    Song.objects.get_or_create(album=sh2, title='The 2nd Hole', audio_file='SIlent_Hill_2_CST_-_5.05_-_The_2nd_Hole_mbeuzk.flac')
    Song.objects.get_or_create(album=sh2, title='Toluca Prison', audio_file='Silent_Hill_2_CST_-_5.06_-_Toluca_Prison_nelgjm.flac')
    Song.objects.get_or_create(album=sh2, title='The 3rd Hole', audio_file='Silent_Hill_2_CST_-_5.07_-_The_3rd_Hole_sijyq7.flac')
    Song.objects.get_or_create(album=sh2, title='The Prison Basement', audio_file='Silent_Hill_2_CST_-_5.08_-_The_Prison_Basement_x18int.flac')
    Song.objects.get_or_create(album=sh2, title='The 4th Hole', audio_file='Silent_Hill_2_CST_-_5.09_-_The_4th_Hole_ogubm3.flac')
    Song.objects.get_or_create(album=sh2, title='Tormented Soul', audio_file='Silent_Hill_2_CST_-_5.10_-_Tormented_Soul_wzequm.flac')
    Song.objects.get_or_create(album=sh2, title='The 5th Hole', audio_file='Silent_Hill_2_CST_-_5.11_-_The_5th_Hole_i0j6ga.flac')
    Song.objects.get_or_create(album=sh2, title='The Labyrinth', audio_file='Silent_Hill_2_CST_-_5.12_-_The_Labyrinth_voqk9h.flac')
    Song.objects.get_or_create(album=sh2, title="Daddy's Revenge", audio_file='Silent_Hill_2_CST_-_5.13_-_Daddy_s_Revenge_wvejmd.flac')
    Song.objects.get_or_create(album=sh2, title='Failing Maria Again', audio_file='Silent_Hill_2_CST_-_5.14_-_Failing_Maria_Again_wyci2x.flac')
    Song.objects.get_or_create(album=sh2, title='Dueling with Eddie', audio_file='Silent_Hill_2_CST_-_5.15_-_Dueling_with_Eddie_rribw8.flac')
    Song.objects.get_or_create(album=sh2, title='Toluca Lake', audio_file='Silent_Hill_2_CST_-_6.01_-_Toluca_Lake_gsuzec.flac')
    Song.objects.get_or_create(album=sh2, title='Lakeview Hotel', audio_file='Silent_Hill_2_CST_-_6.02_-_Lakeview_Hotel_utitcf.flac')
    Song.objects.get_or_create(album=sh2, title='Laura Plays the Piano', audio_file='Silent_Hill_2_CST_-_6.03_-_Laura_Plays_the_Piano_jml3so.flac')
    Song.objects.get_or_create(album=sh2, title='Music Box Melody', audio_file='Silent_Hill_2_CST_-_6.04_-_Music_Box_Melody_ahhkmd.flac')
    Song.objects.get_or_create(album=sh2, title='True', audio_file='Silent_Hill_2_CST_-_6.05_-_True_mdmctv.flac')
    Song.objects.get_or_create(album=sh2, title='Ashes and Tears', audio_file='Silent_Hill_2_CST_-_6.06_-_Ashes_and_Tears_i4wdt6.flac')
    Song.objects.get_or_create(album=sh2, title='Basement Dwellers', audio_file='Silent_Hill_2_CST_-_6.07_-_Basement_Dwellers_laeoyh.flac')
    Song.objects.get_or_create(album=sh2, title="Angela's Hell", audio_file='Silent_Hill_2_CST_-_6.08_-_Angela_s_Hell_m83omh.flac')
    Song.objects.get_or_create(album=sh2, title='Warped Heart', audio_file='Silent_Hill_2_CST_-_6.09_-_Warped_Heart_yz8xtl.flac')
    Song.objects.get_or_create(album=sh2, title='Forced Attrition', audio_file='Silent_Hill_2_CST_-_6.10_-_Forced_Attrition_mnsy2y.flac')
    Song.objects.get_or_create(album=sh2, title='Confronting the Beast', audio_file='Silent_Hill_2_CST_-_7.01_-_Confronting_the_Beast_ywbgga.flac')
    Song.objects.get_or_create(album=sh2, title='Peace & Serenity', audio_file='Silent_Hill_2_CST_-_7.02_-_Peace_Serenity_bzekmp.flac')
    Song.objects.get_or_create(album=sh2, title='Pianissimo Epilogue', audio_file='Silent_Hill_2_CST_-_7.03_-_Pianissimo_Epilogue_omsmi4.flac')
    Song.objects.get_or_create(album=sh2, title='Save Me', audio_file='Silent_Hill_2_CST_-_7.04_-_Save_Me_snzibt.flac')
    Song.objects.get_or_create(album=sh2, title='Theme of Silent Hill 2', audio_file='Silent_Hill_2_CST_-_8.01_-_Theme_of_Silent_Hill_2_ehoy0d.flac')
    Song.objects.get_or_create(album=sh2, title='Leave Ending', audio_file='Silent_Hill_2_CST_-_8.02_-_Leave_Ending_umshuo.flac')
    Song.objects.get_or_create(album=sh2, title='Maria Ending', audio_file='Silent_Hill_2_CST_-_8.03_-_Maria_Ending_inbxel.flac')
    Song.objects.get_or_create(album=sh2, title='In Water Ending', audio_file='Silent_Hill_2_CST_-_8.04_-_In_Water_Ending_ra9tjc.flac')
    Song.objects.get_or_create(album=sh2, title='Rebirth Ending', audio_file='Silent_Hill_2_CST_-_8.05_-_Rebirth_Ending_comb6l.flac')
    Song.objects.get_or_create(album=sh2, title='Wish Ending (part 1)', audio_file='Silent_Hill_2_CST_-_8.06_-_Wish_Ending_part_1_kvc39q.flac')
    Song.objects.get_or_create(album=sh2, title='Wish Ending (part 2)', audio_file='Silent_Hill_2_CST_-_8.07_-_Wish_Ending_part_2_ymdjyo.flac')
    Song.objects.get_or_create(album=sh2, title='UFO Ending', audio_file='Silent_Hill_2_CST_-_8.08_-_UFO_Ending_ialbln.flac')
    Song.objects.get_or_create(album=sh2, title='Dog Ending', audio_file='Silent_Hill_2_CST_-_8.09_-_Dog_Ending_xxl2te.flac')


# Silent Hill 3
    Song.objects.get_or_create(album=sh3, title='Theme of Silent Hill 3', audio_file='Silent_Hill_3_CST_-_1.01_-_Theme_of_Silent_Hill_3_kvaqdg.flac')
    Song.objects.get_or_create(album=sh3, title='Title Screen', audio_file='Silent_Hill_3_CST_-_1.02_-_Title_Screen_lyvh5z.flac')
    Song.objects.get_or_create(album=sh3, title='Save Screen', audio_file='Silent_Hill_3_CST_-_1.03_-_Save_Screen_di4bci.flac')
    Song.objects.get_or_create(album=sh3, title='Begin Nightmare', audio_file='Silent_Hill_3_CST_-_1.04_-_Begin_Nightmare_lqt3fh.flac')
    Song.objects.get_or_create(album=sh3, title='Wicked Horse', audio_file='Silent_Hill_3_CST_-_1.05_-_Wicked_Horse_iyczt6.flac')
    Song.objects.get_or_create(album=sh3, title='The Nightmare to Come', audio_file='Silent_Hill_3_CST_-_1.06_-_The_Nightmare_to_Come_ejxjk2.flac')
    Song.objects.get_or_create(album=sh3, title='Ditching the Detective', audio_file='Silent_Hill_3_CST_-_2.01_-_Ditching_the_Detective_sry6fk.flac')
    Song.objects.get_or_create(album=sh3, title='The Witnesses Arrive', audio_file='Silent_Hill_3_CST_-_2.02_-_The_Witnesses_Arrive_lxvpdk.flac')
    Song.objects.get_or_create(album=sh3, title='Death', audio_file='Silent_Hill_3_CST_-_2.03_-_Death_bb2zrf.flac')
    Song.objects.get_or_create(album=sh3, title='The Calling', audio_file='Silent_Hill_3_CST_-_2.04_-_The_Calling_syi6xu.flac')
    Song.objects.get_or_create(album=sh3, title='Mall Nightmare (Floor 1)', audio_file='Silent_Hill_3_CST_-_2.05_-_Mall_Nightmare_Floor_1_emg2wu.flac')
    Song.objects.get_or_create(album=sh3, title='Mall Nightmare (Floor 2)', audio_file='Silent_Hill_3_CST_-_2.06_-_Mall_Nightmare_Floor_2_h8mezy.flac')
    Song.objects.get_or_create(album=sh3, title='Lair of the Black Worm', audio_file='Silent_Hill_3_CST_-_2.07_-_Lair_of_the_Black_Worm_ymgqu3.flac')
    Song.objects.get_or_create(album=sh3, title='Something Long Forgotten', audio_file='Silent_Hill_3_CST_-_2.08_-_Something_Long_Forgotten_l4znoc.flac')
    Song.objects.get_or_create(album=sh3, title='Subway Trouble', audio_file='Silent_Hill_3_CST_-_2.09_-_Subway_Trouble_iuljgm.flac')
    Song.objects.get_or_create(album=sh3, title='Terror in the Tunnels', audio_file='Silent_Hill_3_CST_-_3.01_-_Terror_in_the_Tunnels_b8ejfk.flac')
    Song.objects.get_or_create(album=sh3, title='Tunnel Ambience', audio_file='Silent_Hill_3_CST_-_3.02_-_Tunnel_Ambience_eeqak6.flac')
    Song.objects.get_or_create(album=sh3, title='Infested Sewer', audio_file='Silent_Hill_3_CST_-_3.03_-_Infested_Sewer_hxosx0.flac')
    Song.objects.get_or_create(album=sh3, title='Office Horrors', audio_file='Silent_Hill_3_CST_-_4.01_-_Office_Horrors_zaxjwx.flac')
    Song.objects.get_or_create(album=sh3, title='Office Nightmare', audio_file='Silent_Hill_3_CST_-_4.02_-_Office_Nightmare_mupkrz.flac')
    Song.objects.get_or_create(album=sh3, title='Meeting Vincent', audio_file='Silent_Hill_3_CST_-_4.02_-_Office_Nightmare_mupkrz.flac')
    Song.objects.get_or_create(album=sh3, title='Monster at the Gate', audio_file='Silent_Hill_3_CST_-_4.04_-_Monster_at_the_Gate_p3vdbp.flac')
    Song.objects.get_or_create(album=sh3, title='A Sad Return Home', audio_file='Silent_Hill_3_CST_-_5.01_-_A_Sad_Return_Home_uidwar.flac')
    Song.objects.get_or_create(album=sh3, title='Battle on the Rooftop', audio_file='Silent_Hill_3_CST_-_5.02_-_Battle_on_the_Rooftop_vf3cgm.flac')
    Song.objects.get_or_create(album=sh3, title='Bitter Tears', audio_file='Silent_Hill_3_CST_-_5.03_-_Bitter_Tears_dh0tlu.flac')
    Song.objects.get_or_create(album=sh3, title='A Will for Revenge', audio_file='Silent_Hill_3_CST_-_5.04_-_A_Will_for_Revenge_nbwtug.flac')
    Song.objects.get_or_create(album=sh3, title='Letter ~ from the Lost Days', audio_file='Silent_Hill_3_CST_-_5.05_-_Letter_from_the_Lost_Days_rtnpjo.flac')
    Song.objects.get_or_create(album=sh3, title='Planning at the Motel', audio_file='Silent_Hill_3_CST_-_5.06_-_Planning_at_the_Motel_zcqjkk.flac')
    Song.objects.get_or_create(album=sh3, title='Town West', audio_file='Silent_Hill_3_CST_-_6.01_-_Town_West_iolkzd.flac')
    Song.objects.get_or_create(album=sh3, title='Return to Brookhaven', audio_file='Silent_Hill_3_CST_-_6.02_-_Return_to_Brookhaven_i0smks.flac')
    Song.objects.get_or_create(album=sh3, title='A Call From Leonard', audio_file='Silent_Hill_3_CST_-_6.03_-_A_Call_From_Leonard_qj8ghp.flac')
    Song.objects.get_or_create(album=sh3, title='Bloody Hallways', audio_file='Silent_Hill_3_CST_-_6.04_-_Bloody_Hallways_ssmxus.flac')
    Song.objects.get_or_create(album=sh3, title='Kill Leonard', audio_file='Silent_Hill_3_CST_-_6.05_-_Kill_Leonard_zqkzyv.flac')
    Song.objects.get_or_create(album=sh3, title="Leonard's Seal", audio_file='Silent_Hill_3_CST_-_6.06_-_Leonard_s_Seal_goohap.flac')
    Song.objects.get_or_create(album=sh3, title='Uninvited Guests', audio_file='Silent_Hill_3_CST_-_6.07_-_Uninvited_Guests_ysjbj7.flac')
    Song.objects.get_or_create(album=sh3, title='Disruption of Order', audio_file='Silent_Hill_3_CST_-_6.08_-_Disruption_of_Order_tjpv0n.flac')
    Song.objects.get_or_create(album=sh3, title='Ringing of Chaos Bells', audio_file='Silent_Hill_3_CST_-_6.09_-_Ringing_of_Chaos_Bells_qbpnop.flac')
    Song.objects.get_or_create(album=sh3, title='The Real Nightmare', audio_file='Silent_Hill_3_CST_-_7.01_-_The_Real_Nightmare_pu2jaq.flac')
    Song.objects.get_or_create(album=sh3, title='Lost Carol (Long Version)', audio_file='Silent_Hill_3_CST_-_7.02_-_Lost_Carol_Long_Version_xdqvth.flac')
    Song.objects.get_or_create(album=sh3, title='Borley Haunted Mansion', audio_file='Silent_Hill_3_CST_-_7.03_-_Borley_Haunted_Mansion_cm86wr.flac')
    Song.objects.get_or_create(album=sh3, title='I Want Love', audio_file='Silent_Hill_3_CST_-_7.04_-_I_Want_Love_pn67mm.flac')
    Song.objects.get_or_create(album=sh3, title='Ghostly Amusement Park', audio_file='Silent_Hill_3_CST_-_7.05_-_Ghostly_Amusement_Park_ehmbur.flac')
    Song.objects.get_or_create(album=sh3, title='Fair Game', audio_file='Silent_Hill_3_CST_-_7.06_-_Fair_Game_lgmjfq.flac')
    Song.objects.get_or_create(album=sh3, title='Carousel of Death', audio_file='Silent_Hill_3_CST_-_7.07_-_Carousel_of_Death_sn0gdq.flac')
    Song.objects.get_or_create(album=sh3, title='Meet Yourself', audio_file='Silent_Hill_3_CST_-_7.08_-_Meet_Yourself_eqrjkk.flac')
    Song.objects.get_or_create(album=sh3, title='Fight Yourself', audio_file='Silent_Hill_3_CST_-_7.09_-_Fight_Yourself_hozfqj.flac')
    Song.objects.get_or_create(album=sh3, title='Clockwork Little Happiness', audio_file='Silent_Hill_3_CST_-_8.01_-_Clockwork_Little_Happiness_h6egpl.flac')
    Song.objects.get_or_create(album=sh3, title='The Dirty Lift', audio_file='Silent_Hill_3_CST_-_8.02_-_The_Dirty_Lift_ijvls3.flac')
    Song.objects.get_or_create(album=sh3, title='Vincent the Pest', audio_file='Silent_Hill_3_CST_-_8.03_-_Vincent_the_Pest_xfvlwt.flac')
    Song.objects.get_or_create(album=sh3, title='Dimented Passages', audio_file='Silent_Hill_3_CST_-_8.04_-_Dimented_Passages_r4ukh9.flac')
    Song.objects.get_or_create(album=sh3, title="Beyond Alessa's Door", audio_file='Silent_Hill_3_CST_-_8.05_-_Beyond_Alessa_s_Door_oftz6v.flac')
    Song.objects.get_or_create(album=sh3, title='Innocent Moon (Sky Edition)', audio_file='Silent_Hill_3_CST_-_8.06_-_Innocent_Moon_Sky_Edition_rfaog7.flac')
    Song.objects.get_or_create(album=sh3, title="Claudia's Sacrifice", audio_file='Silent_Hill_3_CST_-_8.07_-_Claudia_s_Sacrifice_nyqzx9.flac')
    Song.objects.get_or_create(album=sh3, title='Uneternal Sleep', audio_file='Silent_Hill_3_CST_-_8.08_-_Uneternal_Sleep_yifszz.flac')
    Song.objects.get_or_create(album=sh3, title='The Final Battle', audio_file='Silent_Hill_3_CST_-_8.09_-_The_Final_Battle_af6euu.flac')
    Song.objects.get_or_create(album=sh3, title='Memory of the Waters', audio_file='Silent_Hill_3_CST_-_8.10_-_Memory_of_the_Waters_rtwptc.flac')
    Song.objects.get_or_create(album=sh3, title='Cheryl the Blonde', audio_file='Silent_Hill_3_CST_-_8.11_-_Cheryl_the_Blonde_q4cmke.flac')
    Song.objects.get_or_create(album=sh3, title='Hometown', audio_file='Silent_Hill_3_CST_-_8.12_-_Hometown_lqbrxw.flac')
    Song.objects.get_or_create(album=sh3, title='Results', audio_file='Silent_Hill_3_CST_-_8.13_-_Results_dbnqes.flac')
    Song.objects.get_or_create(album=sh3, title='Casual Background', audio_file='Silent_Hill_3_CST_-_8.14_-_Casual_Background_pdlguy.flac')
    Song.objects.get_or_create(album=sh3, title='Rain of Brass Petals (Extended)', audio_file='Silent_Hill_3_CST_-_9.01_-_Rain_of_Brass_Petals_Extended_t5gwpb.flac')
    Song.objects.get_or_create(album=sh3, title='No Excuses', audio_file='Silent_Hill_3_CST_-_9.02_-_No_Excuses_mj23sk.flac')
    Song.objects.get_or_create(album=sh3, title="I've Been Losing You", audio_file='Silent_Hill_3_CST_-_9.03_-_I_ve_Been_Losing_You_duxjgx.flac')
    Song.objects.get_or_create(album=sh3, title='All Screwed Up', audio_file='Silent_Hill_3_CST_-_9.04_-_All_Screwed_Up_lxvuke.flac')
    Song.objects.get_or_create(album=sh3, title='Dance Girl Dance', audio_file='Silent_Hill_3_CST_-_9.05_-_Dance_Girl_Dance_tricnb.flac')
    Song.objects.get_or_create(album=sh3, title='Rain of Brass Petals (3 Vocals)', audio_file='Silent_Hill_3_CST_-_9.06_-_Rain_of_Brass_Petals_3_Vocals_lyicpn.flac')

    print("Database seeded successfully.")

if __name__ == "__main__":
    populate_database()